config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'

  resources :places
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  has_one :weather
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable
  extend Enumerize
  enumerize :role, :in => { admin: 0, user: 1 }, scope: true
end

app/models/weather.rb
class Weather < ApplicationRecord
  belongs_to :place
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user, except: [:index, :show]

  def index
    @places = Place.all
  end

  def new
    @place = Place.new
  end

  def show
    @place = Place.includes(:weather).find(params[:id])
    @weather = @place.weather
    if @weather
      unless @weather.updated_at > 10.minutes.ago
        @weather.update(OpenWeatherCaller.current_weather_at @place)
      end
    else
      @weather = @place.create_weather OpenWeatherCaller.current_weather_at @place
    end
  end

  def create
    @place = Place.new place_params
    if @place.save
      redirect_to places_path
    else
      render :new
    end
  end

  def update
    @place = Place.find params[:id]
    if @place.update place_params
      redirect_to places_path
    else
      render :edit
    end
  end

  def edit
    @place = Place.find params[:id]
  end

  def destroy
    @place = Place.find params[:id]
    @place.delete
    redirect_to places_path
  end

  private

  def authorize_user
    unless current_user.role == :admin
      redirect_to places_path
    end
  end

  def place_params
    params.require(:place).permit :lat, :lon, :address
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_top_navbar.html.slim
nav.navbar.navbar-inverse.navbar-static-top
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a class="navbar-brand" href=root_path AT Consulting Test
    #navbar.navbar-collapse.collapse
      - if current_user
        ul.nav.navbar-nav.navbar-right
          li.active
            a href="#"
              = current_user.email
          li
            = link_to 'Выход', destroy_user_session_path, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    title AtConsultingTest
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  body
    = render 'layouts/top_navbar'
    .container-fluid
      = yield
  = yield :custom_js

app/views/places/_form.html.slim
#map style="height: 300px" data-editable='true'
br
= form_for place do |f|
  = f.hidden_field :lat
  = f.hidden_field :lon
  .form-group.col-xs-12
    = f.label :address
    = f.text_field :address, class: 'form-control'
  = f.submit (place.id ? 'Update' : 'Save'), class: 'btn btn-primary'

app/views/places/edit.html.slim
= content_for :custom_js do
  script src="//maps.googleapis.com/maps/api/js?key=#{Rails.application.secrets.google_maps_api_key}&sensor=false&libraries=places&language=ru&callback=initMap"
.container
  = render 'form', place: @place

app/views/places/index.html.slim
.container
  .panel.panel-default
    .panel-heading Места
    table.table.table-striped
      thead
        tr
          th Адрес
          th
          - if current_user.role == :admin
            th 
      tbody
        - @places.each do |place|
          tr
            td = place.address
            td 
              = link_to 'Узнать погоду', place_path(place), class: 'btn btn-primary'
            - if current_user.role == :admin
              td
                = link_to 'Редактировать', edit_place_path(place), class: 'btn btn-primary', style: 'margin-right: 5px'
                = link_to 'Удалить', place_path(place), class: 'btn btn-danger', method: :delete
  - if current_user.role == :admin
    = link_to 'Добавить место', new_place_path, class: 'btn btn-primary'

app/views/places/new.html.slim
= content_for :custom_js do
  script src="//maps.googleapis.com/maps/api/js?key=#{Rails.application.secrets.google_maps_api_key}&sensor=false&libraries=places&language=ru&callback=initMap"
.container
  = render 'form', place: @place

app/views/places/show.html.slim
= content_for :custom_js do
  script src="//maps.googleapis.com/maps/api/js?key=#{Rails.application.secrets.google_maps_api_key}&sensor=false&libraries=places&language=ru&callback=initMap"
.container
  h5 = @place.address
  #map data-editable=false style="height: 300px"
  = hidden_field_tag :lat, @place.lat, id: 'place_lat'
  = hidden_field_tag :lon, @place.lon, id: 'place_lon'
  ul.list-group
    li.list-group-item = "Описание: #{@weather.description}"
    li.list-group-item = "Температура: #{@weather.temp.to_s}"
    li.list-group-item = "Температура минимальная: #{@weather.temp_min}"
    li.list-group-item = "Температура максимальная: #{@weather.temp_max}"
    li.list-group-item = "Давление: #{@weather.pressure}"